---
title: "Lab3_YZ_EDA"
author: "Yulia Zamriy"
date: "March 18, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "latex")
```

```{r}
#install.packages("kableExtra")
#install.packages("viridisLite")
#install.packages("viridis")
#install.packages("Hmisc")
# install.packages("car")
# install.packages("lmtest")
# install.packages("sandwich")
# install.packages("stargazer")
library(knitr)
library(kableExtra)
library(Hmisc)
library(reshape2)
library(ggplot2)
library(car)
library(lmtest)
library(sandwich)
library(stargazer)
```

```{r}
#setwd("/home/yulia/Documents/MIDS/W203/Lab_3/")
crime <- read.csv("crime_v2.csv", stringsAsFactors = FALSE)
crime <- na.omit(crime)
```

```{r}
summary(crime$crmrte)
```

```{r}
par(mfrow=c(1,2))
hist(crime$crmrte, breaks = 15)
hist(log(crime$crmrte), breaks = 15)
```

```{r}
crime$prbconv <- as.numeric(crime$prbconv)
```


```{r}
summary(crime$prbarr)
summary(crime$prbconv)
summary(crime$prbpris)
```

```{r}
nrow(crime[crime$prbarr >= 1,])
```
```{r}
nrow(crime[crime$prbconv >= 1,])
```

```{r}
crime$exclude <- 0
crime[crime$prbarr > 1,]$exclude <- 1
crime[crime$prbconv > 1,]$exclude <- 1
table(crime$exclude)
```

```{r}
summary(crime$avgsen)
```
```{r}
summary(crime$polpc)
```

```{r}
summary(crime$density)
```

```{r}
summary(crime$taxpc)
```

```{r}
mean(crime$west)
mean(crime$central)
mean(crime$urban)
```

```{r}
summary(crime$pctmin80)
```

```{r}
summary(crime$wcon)
```

```{r}
summary(crime$wtuc)
```

```{r}
summary(crime$wtrd)
```

```{r}
summary(crime$wfir)
```

```{r}
summary(crime$wser)
```

```{r}
summary(crime$wmfg)
```

```{r}
summary(crime$wfed)
```

```{r}
summary(crime$wsta)
```

```{r}
summary(crime$wloc)
```

```{r}
summary(crime$mix)
```

```{r}
summary(crime$pctymle)
```

```{r}
crime[crime$wser > 2000,]$exclude <- 1
crime_sub <- subset(crime, exclude == 0)
crime_sub$exclude <- NULL
```


```{r}
# Prepare a .RData for easier sharing and usage.
ind_variables <- c(
  'prbarr', 'prbconv', 'prbpris', 'avgsen', 
  'polpc', 'density', 'taxpc', 'west', 'central', 'urban', 'pctmin80', 'wcon', 
  'wtuc', 'wtrd', 'wfir', 'wser', 'wmfg', 'wfed', 'wsta', 'wloc', 'mix', 
  'pctymle'
)
var_labels <- c(
  'probability of arrest', 'probability of conviction', 
  'probability of prison sentence', 'avg. sentence, days', 
  'police per capita', 'people per sq. mile', 'tax revenue per capita', 
  '=1 if in western N.C.', '=1 if in central N.C.', '=1 if in SMSA', 
  'perc. minority, 1980', 'weekly wage, construction', 
  'wkly wge, trns, util, commun', 'wkly wge, whlesle, retail trade', 
  'wkly wge, fin, ins, real est', 'wkly wge, service industry', 
  'wkly wge, manufacturing', 'wkly wge, fed employees', 
  'wkly wge, state employees', 'wkly wge, local gov emps', 
  'offense mix: face-to-face/other', 'percent young male'
)
impact <- c("Negative" , "Negative", "Negative", "Negative",
            "Negative", "Positive", "Negative", 
            "Unclear", "Unclear", "Unclear", "Unclear",
            "Negative","Negative","Negative",
            "Negative", "Negative", "Negative", "Negative",
            "Negative", "Negative", "Unclear","Positive")
control <- c("Yes", "Yes", "Yes", "Yes",
             "Yes", "No", "Yes", 
             "No", "No", "No","No",
             "Yes", "Yes", "Yes",
             "Yes", "Yes", "Yes", "Yes", 
             "Yes", "Yes", "No", "No")
cor_w_crimerate <- round(cor(crime_sub)[3,-c(1,2,3)],2)
desc <- data.frame(ind_variables, var_labels, impact, cor_w_crimerate, control,
                   row.names = NULL)
colnames(desc) <- c("Explanatory Variables", 
                    "Explanation", 
                    "Expected Impact on Crime Rate",
                    "Correlation w/ Crime Rate",
                    "Can Gov Impact This?")
```

```{r table1, as.is = TRUE}
kable(desc, booktabs = TRUE, align = c("llccc")) %>%
  kable_styling(latex_options = c("scale_down"),
                full_width = FALSE) %>% 
  row_spec(0, bold = TRUE) %>% 
  column_spec(1, width = "8em") %>% 
  column_spec(3, width = "10em") %>% 
  column_spec(4, width = "8em") %>% 
  column_spec(5, width = "9em")
```


```{r}
crime_sub$othergeo <- ifelse(crime_sub$west == 0 & crime_sub$central == 0, 1, 0)
mean(crime_sub$west)
mean(crime_sub$central)
mean(crime_sub$othergeo)
```

```{r}
crime_cor <- cor(crime_sub)[3,-c(1,2,3)]
crime_cor <- crime_cor[order(crime_cor)]
```

```{r}

crime_cor_lab <- ifelse(crime_cor < 0, crime_cor-0.15, crime_cor)

par(mar = c(2,8,1,0))
b <- barplot(crime_cor,
        col = ifelse(crime_cor < 0, "red","blue"),
        horiz = TRUE,
        las = 1,
        xaxt = "n",
        xlim = c(-1,1),
        main = "Correlation of Crime Rate with Other Variables")
text(x = crime_cor_lab, 
     y = b, 
     label = round(crime_cor,2), 
     pos = 4, 
     cex = 0.6)
axis(1, 
     at = seq(-1,1, by = 0.2), 
     labels = seq(-1,1, by = 0.2),
     cex.axis = 0.6)
```

```{r}
cor_mat <- round(cor(crime_sub[-c(1:3)]),2)
get_upper_tri <- function(cor_mat){
    cor_mat[lower.tri(cor_mat)]<- NA
    return(cor_mat)
}
cor_mat_upper <- get_upper_tri(cor_mat)
cor_mat_upper2 <- melt(cor_mat_upper, na.rm = TRUE)
cor_mat_upper2[cor_mat_upper2$value == 1,]$value <- 0
```

```{r}
ggplot(data = cor_mat_upper2, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white",
                        midpoint = 0, limit = c(-1,1), space = "Lab",
                        name = "Correlation") +
  theme_minimal() +
  scale_x_discrete(position = "top") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 8, hjust = 0),
        axis.title.x=element_blank(),
        axis.title.y=element_blank()) +
  coord_fixed()
```

```{r}
crime_sub$region <- ifelse(crime_sub$west == 1, "west",
                           ifelse(crime_sub$central == 1, "central", "other"))
```

```{r}
crmrte_reg <- aggregate(crmrte ~ region, data = crime_sub, mean)
density_reg <- aggregate(density ~ region, data = crime_sub, mean)
urban_reg <- aggregate(urban ~ region, data = crime_sub, mean)
polpc_reg <- aggregate(polpc ~ region, data = crime_sub, mean)
cbind(crmrte_reg, density_reg[2], polpc_reg[2])
```

```{r}
ggplot(crime_sub, aes(density, crmrte)) +
  geom_point() +
  facet_grid(region~.) +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
ggplot(crime_sub, aes(polpc, crmrte)) +
  geom_point() +
  facet_grid(region~.) +
  geom_smooth(method = "lm", se = FALSE)
```


```{r}
ggplot(crime_sub, aes(pctymle, crmrte)) +
  geom_point() +
  facet_grid(region~.) +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
ggplot(crime_sub, aes(taxpc, crmrte)) +
  geom_point() +
  facet_grid(region~.) +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
ggplot(crime_sub, aes(avgsen, crmrte)) +
  geom_point() +
  facet_grid(region~.) +
  geom_smooth(method = "lm", se = FALSE)
```


```{r}
ggplot(crime_sub, aes(taxpc, polpc)) +
  geom_point() +
  facet_grid(region~.) +
  geom_smooth(method = "lm", se = FALSE)
```
```{r}
ggplot(crime_sub, aes(pctymle, polpc)) +
  geom_point() +
  facet_grid(region~.) +
  geom_smooth(method = "lm", se = FALSE)
```


```{r}
vars_wages <- c("wcon", "wtuc", "wtrd", "wfir",
              "wser", "wmfg", "wfed", "wsta", "wloc")
crime_sub[paste(vars_wages,"ln",sep = ".")] <- log(crime_sub[vars_wages])
crime_sub[paste(vars_wages,"sq",sep = ".")] <- (crime_sub[vars_wages])**2

crime_sub_w1 <- subset(crime_sub, select = c("crmrte", vars_wages))
crime_sub_w2 <- subset(crime_sub, select = c("crmrte", paste(vars_wages,"ln",sep = ".")))
crime_sub_w3 <- subset(crime_sub, select = c("crmrte", paste(vars_wages,"sq",sep = ".")))
wages_cor <- cbind(round(cor(crime_sub_w1)[1,-1],2),
                   round(cor(crime_sub_w2)[1,-1],2),
                   round(cor(crime_sub_w3)[1,-1],2))
colnames(wages_cor) <- c("As is", "Log", "Squared")
wages_cor <- melt(wages_cor)
colnames(wages_cor) <- c("Wages", "Transformation", "Correlation")

ggplot(data = wages_cor, aes(Wages, Correlation, fill = Transformation)) +
  geom_col(position = "dodge")
```

```{r}
vars_other <- c("prbarr", "prbconv", "prbpris", "avgsen", "polpc", "density", "taxpc",
               "pctmin80", "mix", "pctymle")
crime_sub[paste(vars_other,"sq",sep = ".")] <- (crime_sub[vars_other])**2

crime_sub_o1 <- subset(crime_sub, select = c("crmrte", vars_other))
crime_sub_o2 <- subset(crime_sub, select = c("crmrte", paste(vars_other,"sq",sep = ".")))
others_cor <- cbind(round(cor(crime_sub_o1)[1,-1],2),
                   round(cor(crime_sub_o2)[1,-1],2))
colnames(others_cor) <- c("As is", "Squared")
others_cor <- melt(others_cor)
colnames(others_cor) <- c("OtherVars", "Transformation", "Correlation")

ggplot(data = others_cor, aes(OtherVars, Correlation, fill = Transformation)) +
  geom_col(position = "dodge")
```

```{r}
ind_vars1 <- c("density", "prbarr", "polpc", "taxpc","pctymle","pctmin80")
crmrte_formula1 <- as.formula(paste("crmrte ~", paste(ind_vars1, collapse = "+"), sep = ""))
crmrte_lm1 <- lm(crmrte_formula1, data = crime_sub)
summary(crmrte_lm1)
```

```{r}
ind_vars_all <- c("prbarr", "prbconv", "prbpris", "avgsen", "polpc", "density", "taxpc",
               "west", "central", "urban", "pctmin80", "wcon", "wtuc", "wtrd", "wfir",
               "wser", "wmfg", "wfed", "wsta", "wloc", "mix", "pctymle")

crmrte_formula_all <- as.formula(paste("crmrte ~", paste(ind_vars_all, collapse = "+"), sep = ""))
# crmrte_lm0 <- lm(crmrte ~ 1,
#                  data = crime_sub)
crmrte_lm_all <- lm(crmrte_formula_all,
                 data = crime_sub)
crmrte_lm_step <- step(crmrte_lm1, scope=list(lower=crmrte_lm1, upper=crmrte_lm_all), 
                       direction="both",
                       trace = FALSE)
summary(crmrte_lm_step)
```

```{r}
sel_vars_pvals <- summary(crmrte_lm_step)$coefficients[-1,4]
sel_vars <- names(sel_vars_pvals[sel_vars_pvals < 0.05])

sel_vars_cut <- c("density",  "prbarr",   "polpc",    "taxpc",
                "pctymle", "pctmin80", "wsta")
sel_vars_transf <- c("density",  "prbarr",   "polpc",  "polpc.sq",  "taxpc", "taxpc.sq",
                     "pctymle", "pctmin80")
```


```{r}
max_vals <- data.frame(t(mapply(summary, crime_sub[,sel_vars_cut])[5:6,]))
max_vals$Benchmarks <- round((max_vals$Max. - max_vals$X3rd.Qu.)/1.5 + max_vals$X3rd.Qu.,4)
crime_sub$density_outl <- ifelse(crime_sub$density > max_vals["density",]$Benchmarks, 1, 0)
crime_sub$prbarr_outl <- ifelse(crime_sub$prbarr > max_vals["prbarr",]$Benchmarks, 1, 0)
crime_sub$polpc_outl <- ifelse(crime_sub$polpc > max_vals["polpc",]$Benchmarks, 1, 0)
crime_sub$taxpc_outl <- ifelse(crime_sub$taxpc > max_vals["taxpc",]$Benchmarks, 1, 0)
crime_sub$pctymle_outl <- ifelse(crime_sub$pctymle > max_vals["pctymle",]$Benchmarks, 1, 0)
crime_sub$pctmin80_outl <- ifelse(crime_sub$pctmin80 > max_vals["pctmin80",]$Benchmarks, 1, 0)
crime_sub$wsta_outl <- ifelse(crime_sub$wsta > max_vals["wsta",]$Benchmarks, 1, 0)

sel_vars_cut_outl <- paste(sel_vars_cut, "outl", sep = "_")
crime_sub$outliers <- rowSums(crime_sub[,sel_vars_cut_outl])
mapply(sum, crime_sub[,sel_vars_cut_outl])
table(crime_sub$outliers)
```

```{r}
crmrte_formula2 <- as.formula(paste("crmrte ~", paste(sel_vars_cut, collapse = "+"), sep = ""))
crmrte_formula2sq <- as.formula(paste("crmrte ~", paste(sel_vars_transf, collapse = "+"), sep = ""))

crmrte_lm2 <- lm(crmrte_formula2, data = crime_sub)
crmrte_lm2sq <- lm(crmrte_formula2sq, data = crime_sub)

summary(crmrte_lm2sq)
crmrte_lm2sq_out <- lm(crmrte_formula2sq, data = subset(crime_sub, outliers == 0))
cbind(summary(crmrte_lm2sq)$coefficients[,3], summary(crmrte_lm2sq_out)$coefficients[,3])
```

```{r}
sel_vars_inter <- c("density",  "prbarr",   "polpc",  
               "pctymle", "pctmin80", "wsta", "west*polpc")

crmrte_formula3 <- as.formula(paste("crmrte ~", paste(sel_vars_inter, collapse = "+"), sep = ""))
crmrte_lm3 <- lm(crmrte_formula3, data = crime_sub)
summary(crmrte_lm3)
crmrte_lm3_out <- lm(crmrte_formula3, data = subset(crime_sub, outliers == 0))
cbind(summary(crmrte_lm3)$coefficients[,3], summary(crmrte_lm3_out)$coefficients[,3])
```

```{r}
crime_sub$crmrte.ln = log(crime_sub$crmrte)
crmrte_formula3.ln <- as.formula(paste("crmrte.ln ~", paste(sel_vars_inter, collapse = "+"), sep = ""))
crmrte_lm3.ln <- lm(crmrte_formula3.ln, data = crime_sub)
summary(crmrte_lm3.ln)
cbind(summary(crmrte_lm3)$coefficients[,3], summary(crmrte_lm3.ln)$coefficients[,3])
```


```{r}
plot(crmrte_lm3)
```

```{r}
par(mfrow=c(1,2))
hist(crmrte_lm2$residuals, breaks = 15)
#hist(crmrte_lm2sq$residuals, breaks = 15)
hist(crmrte_lm3$residuals, breaks = 15)
#hist(crmrte_lm3.ln$residuals, breaks = 15)
```

```{r}
shapiro.test(crmrte_lm3$residuals)
```

```{r}
bptest(crmrte_lm3)
```

```{r}
coeftest(crmrte_lm3, vcov = vcovHC)
```


```{r}
anova(crmrte_lm2,crmrte_lm3)
```

```{r}
se.crmrte_lm2 <- sqrt(diag(vcovHC(crmrte_lm2)))
se.crmrte_lm3 <- sqrt(diag(vcovHC(crmrte_lm3)))
stargazer(crmrte_lm2,crmrte_lm3,
          type = "text", omit.stat = "f",
          se = list(se.crmrte_lm2, se.crmrte_lm3),
          star.cutoffs = c(0.05, 0.01, 0.001))
```


```{r}
showScatterPlotMatrices <- function(dependent, independents, data) {
  make.formula <- function(independent) {
    f <- paste(c(dependent, independent), collapse = ' ~ ')
    return(as.formula(f))
  }
  formulas <- mapply(make.formula, independents)
  plot.relation <- function(f) {
    model <- lm(f, data = data)
    r2 <- round(summary(model)$r.squared,2)
    description <- 
      as.character(desc$Explanation[as.character(desc$`Explanatory Variables`) == as.character(f[3])])
    xval <- 
      summary(eval(parse(text =
                           paste(deparse(substitute(data)),names(model$coefficients[2]),sep="$"))))[2]
    par(mar = c(4,4,4,4))
    plot(f,
         data = data,
         main = paste(c('Effect of', description, 'on crime rate')))
    abline(model, col = "darkblue")
    text(x = xval, y = 0.09, bquote(R^2 == .(r2)), col = "darkblue")
  }
  mapply(plot.relation, formulas)
}
#wage_vars <- colnames(crime_sub)[grep("w", colnames(crime_sub))][-1]
plots <- showScatterPlotMatrices('crmrte', sel_vars_cut, crime_sub)
```




